const simpleSentences = [
  // https://simple.m.wikipedia.org/wiki/1910_Cuba_hurricane
  'It grew stronger as it moved northwest.',
  'It then made landfall on the western end of Cuba.',
  'The storm made a loop over open water, and then began moving towards the United States.',
  "Because of the storm's loop, some reports said it was actually two hurricanes.",
  "In Cuba, the storm was one of the worst disasters in the island's history.",
  'There was bad damage and thousands of people lost their homes.',
  'In Florida, the storm also caused damage and caused flooding in some areas.',
  'It is not known exactly how much damage the storm caused.',
  'It was north of Panama.',
  'The storm grew stronger while it moved toward the northwest.',
  'The storm then hit western Cuba and crossed the island.',
  'Now over land, the hurricane became weaker.',
  'It was considered one of the worst tropical cyclones on the island.',
  'Strong winds and a lot of rain caused flooding in streets, ruined crops, and damaged farms.',
  "The country's capital, Havana, also suffered bad damage.",
  'On the coast, many ships carrying valuable items sunk.',
  ' Early Saturday morning we got the full force of the storm.',
  'The seas came from all directions, though it was from the starboard that the real trouble seemed to come.',
  'A steamboat called the Harold saw the ship and rescued all of the crew.',
  'The crew told the captain that the ship would be unable to float in five more hours.',
  'One man near Lemon city was killed by falling wood.',
  "However, the storm's effects on the east coast of Florida were not as bad as they were in other places.",

  // https://en.m.wikipedia.org/wiki/COVID-19_pandemic
  `Loss of sense of smell was also common.`,
  `Common symptoms are fever, cough, and fatigue.`,
  `All pubs and gyms were to close as soon as possible.`,
  `Many governments have asked people to self-quarantine.`,
  `Primary treatment is symptomatic and supportive therapy.`,
  `There is no known vaccine or specific antiviral treatment.`,
  `Those who may have it were advised to wear a mask in public.`,
  `The virus was first noted to have spread to Spain on 31 January.`,
  `Hand washing is recommended to prevent the spread of the disease.`,
  `Iran reported its first confirmed cases of infections on February.`,
  `It is most contagious during the first 3 days after the onset of symptoms.`,
  `It was reported that all new overseas arrivals will be quarantined for 2 weeks.`,
  `The Italian government ordered the full closure of all schools and universities.`,
  `Spread can happen before symptoms appear even from people who don't show symptoms.`,
  `The droplets usually fall to the ground or onto surfaces rather than travelling through air over long distances.`,
  `The time from exposure to onset of symptoms is typically around five days but may range from two to fourteen days.`,
  `Many governments have restricted or advised against all non-essential travel to and from areas affected by the outbreak.`,
  `The virus is spread between people during close contact, often via small droplets produced by coughing, sneezing, and talking.`,

  // https://simple.m.wikipedia.org/wiki/COVID-19_pandemic
  'This infected another animal, possibly a pangolin.',
  'People usually cough and have difficulty breathing.',
  'However, there were large differences between different age groups and between men and women.',
  'Men were more likely to die than women.',
  'This was not only in large cities but also in rural areas.',
  'This was not only for old people but for people in all age groups.',
  'There were three hospitalized Asian patients for every two hospitalized white patients.',
  'Hospitals may be a long distance away, and racism can affect the way doctors and nurses react.',
  'They also used radio stations.',
  'They said the best plan was for whole communities to decide to isolate.',
  'There were weeks of protests all over the world against police racism.',
  'There were clusters popping up all over New Zealand including one at a wedding and one at a rest home.',
  'Even so not many have died, the numbers are in the teens.',
  'The pandemic made it more difficult for millions of people all over the world to get enough food.',
  'People lost their jobs, so they did not have money to buy food.',
  'Farms were shut down, so there was less food made.',
  'Because nursing homes had stopped allowing visitors, it took longer for them to get caught.',
  'They said it was important to watch the wildlife trade, like in the Wuhan wet market.',

  // https://simple.m.wikipedia.org/wiki/Saturn
  'These rings are made of ice with smaller amounts of rocks and dust.',
  'Some people believe that the rings were caused from a moon impact or other event.',
  'Saturn is the only planet in the solar system that is less dense than water.',
  "Saturn's clouds are much fainter and the bands are wider at the equator.",
  'However scientists do not agree about this.',
  'These oval spots are cyclonic storms, the same as cyclones seen on Earth.',
  'Unlike the north pole, the south pole does not show any hexagonal cloud feature.',
  "Saturn's field is a magnetic dipole.",
  "Saturn's rotational period is calculated by the rotation speed of radio waves released by the planet.",
  'He thought that Saturn was three separate planets that almost touched one another.',
  'Though the rings appear to be solid and unbroken when viewed from above, the rings are made of small particles of rock and ice.',
  "Scientists believe this is caused by the gravitational force of some of Saturn's moons.",
  "The rings' atmosphere is made of oxygen gas, and it is produced when the Sun's ultraviolet light breaks up the water ice in the rings.",
  'Chemical reaction also occurs between the ultraviolet light and the water molecules, creating hydrogen gas.',
  'However, what causes the spokes to form is still unknown.',
  'One part of this satellite then landed on Titan.',
  'It took photographs of the planet and a few of its moons, but were low in resolution.',
  'It discovered a new, thin ring called the F ring.',
  'It also discovered that the dark ring gaps appear bright when viewed towards the Sun, which shows the gaps are not empty of material.',
  'These photos were able to show the surface features of the moons.',
  'Photos taken by the space probe showed that changes were happening to the rings and atmosphere.',
  "The Voyager spacecrafts discovered a number of moons orbiting close to Saturn's rings, as well as discovering new ring gaps.",
  'Before then, it flew close and took high resolution photos of its surface.',
  'It landed on a dry surface, but it found that large bodies of liquid exist on the moon.',
  'The Cassini probe continued to collect data from Titan and a number of the icy moons.',

  // https://simple.m.wikipedia.org/wiki/Violin
  'Different notes are made by fingering with the left hand while bowing with the right.',
  'Unlike guitar, it has no frets or other markers on the fingerboard.',
  'A person who makes or repairs violins is called a luthier.',
  'The violin is important in European and Arabian music.',
  'No other instrument has played such an important part in Europe.',
  'Nearly every composer wrote for the violin.',
  'This word can be used as a nickname for the violin.',
  'It is properly used when talking about folk music.',
  'Some of the instruments that they made are still here today.',
  'They are kept in museums all around the world.',
  'This acts as a resonating box.',
  'It makes the vibrating strings sound louder.',
  'Many of the parts of the violin are named after parts of the body.',
  'The strings go across the bridge halfway between the end of the finger board and the tail piece.',
  'The bridge is not fixed onto the violin.',
  'It is held in place by the strings.',
  'The strings keep it in place because they are so tight.',
  'If the strings are completely loosened, the bridge will not stay on.',
  'The bridge helps to send the vibrations of the strings down to the body of the instrument.',
  'This is a small piece of wood.',
  'It looks like a small finger.',
  'It goes from the belly to the back.',
  'The soundpost is also held in place by the strings.',
  'In the middle of the belly there are two long, curved holes.',
  'This is because of their shape.',
  'The top of the strings are wound around pegs.',
  'The violin can be tuned by turning the pegs.',
  'The very top of the neck is called the scroll.',
  'Violins today also have a chinrest.',
  "This helps to hold the violin against the player's shoulder.",
  'A shoulder rest can also be used.',
  'These are now made of foam.',
  'They have special legs to hold them on to the violin.',
  'Many beginners prefer to use a sponge and an elastic band instead.',
  'These adjusters go through holes in the tailpiece.',
  'They stop the strings from slipping when being tuned.',
  'Strings used to be made of gut.',
  'They are now mostly made of steel or nylon.',
  'Adjusters can only be used with some strings.',
  'The front of the violin body is made of spruce.',
  'The back and sides of the body are made of maple.',
  'The bow can be made of several kinds of wood.',
  'An example would be pernambuco.',
  'Some players today use bows made of carbon fibre.',
  'The bow is strung with horsehair.',
  'It takes years of practice to become a good violinist.',
  'A beginner will start with pieces and or exercises that do not require precise or complicated technique in right or left hand.',
  'Some examples of pieces that do not require great technique are Twinkle Twinkle Little Star by Mozart, and Over the Rainbow.',
  'As the musician develops more and more confidence and skill in both left and right hand, pieces and exercises will become progressively more difficult.',
  'When necessary, they will also learn techniques and skills that will enhance their playing.',
  'Vibrato, smooth bow changes in the right hand, and shifting.',
  'This is called intonation.',
  'The musician will also learn vibrato.',
  'This changes the intonation of each note slightly by making it a little bit sharper, then a little bit flatter, producing a kind of wobble.',
  'This is important in many styles of music to create mood.',
  'Besides plucking, there are many special effects.',
  'There is also double stopping, chords, and scordatura tuning.',
  'The violin can be played either standing or sitting down.',
  'When playing solo music the violinist normally stands.',
  'When playing in chamber music or in orchestras the violinist sits, but this was not always the case.',
  'When sitting, the violinist may have to turn his or her right leg in so that it does not get in the way of the bow.',
  'Many of these composers were from Italy.',
  'They were themselves violinists.',
  'They also wrote a large amount of chamber music, especially string quartets.',
  'In the Romantic period many virtuoso violin works were written.',
  'He composed and played violin music that was harder than anything that had been written before.',

  // https://simple.m.wikipedia.org/wiki/Victoria_line
  'On the Tube map it is shown with a light blue color.',
  'The stations are on top of small hills, or humps.',
  'As the train travels up the hill to the station its weight helps it to slow down.',
  'As the train leaves the station it travels down the hill, with gravity helping the train to speed up.',
  'In some cases this was achieved by placing the Victoria line platforms on either side of the station.',
  'Each station was decorated with tiled motifs on seating recesses to tell them apart from each other.',
  'As a result, the station standards were lower than on older lines and on later projects.',
  'This also affects lighting levels.',
  'At most stations, there is a concrete staircase where more escalators could be installed.',
  'It can cause severe congestion at peak times.',
  'The tube station would be on a large reversing loop with one platform.',
  'This would remove a problem of having too many trains by getting rid if the need for trains to reverse at Brixton.',
  'However, this would cost too much money for how little it would actually help passengers.',
  'It is the only part of the line not in tunnel.',

  // https://simple.m.wikipedia.org/wiki/Oxygen
  'Oxygen is a chemical element.',
  'It is the third most common element in the universe.',
  'This gas is often just called oxygen.',
  'It has no taste or smell.',
  'It is pale blue when it is liquid or solid.',
  'It is a very reactive nonmetal.',
  'It makes oxides and other compounds with many elements.',
  "The oxygen in these oxides and in other compounds makes up nearly half of the Earth's crust, by mass.",
  'Oxygen is the element which most life uses in respiration.',
  'Many molecules in living things have oxygen in them such as proteins.',
  'Oxygen is a part of water, which all known life needs to live.',
  'Priestley is usually thought to be the main discoverer because his work was published first.',
  'He was the first person to say it was a chemical element.',
  'He was also right about how it helps combustion work.',
  'It is then absorbed, which means less radiation reaches ground level.',
  'Oxygen gas is used for making steel, plastics and textiles.',
  'It also has medical uses and is used for breathing when there is no good air, and for welding.',
  'From this, he worked out that oxygen is used for both respiration and combustion.',
  'Things that corrode, like iron, were thought to contain very little.',
  'Some people believe this was the discovery of oxygen while others disagree.',
  'He also found that air rushed in when the container was opened.',
  'After this, he found that the weight of the tin had increased by the same amount as the weight of the air that rushed in.',
  "John Dalton's theory of atoms said that all elements had one atom and atoms in compounds were usually alone.",
  'This was then also evaporated to cool oxygen gas in order to turn it into a liquid.',
  'This bond can be called many things, but simply called a covalent double bond.',
  'Oxygen gas is very reactive and can react with many other elements.',
  'Oxides are made when metal elements react with oxygen, such as iron oxide, which is known as rust.',
  'There are a lot of oxide compounds on Earth.',
  "This is the second biggest part of the Earth's atmosphere.",
  'Oxygen dissolves more easily from air into water than nitrogen does.',
  'Earth is strange compared to other planets, as a large amount of its atmosphere is oxygen gas.',
  'The much higher amount of oxygen gas around Earth is because of the oxygen cycle.',
  'The hydrogen combines with carbon dioxide to make carbohydrates.',
  'It then takes oxygen gas out of the atmosphere and turns it into carbon dioxide and water.',
  'Because of this, it is used in medicine.',
  'It is used to increase the amount of oxygen in a persons blood so more respiration can take place.',
  'This can make them become healthy quicker if they are ill.',
  'Pure oxygen is used but at a much lower pressure.',
  'This removes any sulfur or carbon from the ore that would not be wanted.',
  'They are given off as sulfur oxide and carbon dioxide.',
  'It is the most common oxide on Earth.',
  'All known life needs water to live.',
  'These bonds give oxides.',
  "Most metal's surfaces are turned into oxides when in air.",
  "Iron's surface will turn to rust when in air for a long time.",
  'There are small amounts of carbon dioxide in the air.',
  'Many organic solvents also have oxygen, such as acetone.',

  // https://simple.m.wikipedia.org/wiki/Forest
  'A forest is a piece of land with many trees.',
  'Many animals need forests to live and survive.',
  'Forests are very important and grow in many places around the world.',
  'They are an ecosystem which includes many plants and animals.',
  'Temperature and rainfall are the two most important things for forests.',
  'Many places are too cold or too dry for them.',
  'Forests can exist from the equator to near the polar regions, but different climates have different kinds of forests.',
  'In cold climates conifers dominate, but in temperate zone and tropical climates forests are mainly made up of flowering plants.',
  'Different rainfall also makes different kinds of forest.',
  'No forests exist in deserts, just a few trees in places where their roots can get at some underground water.',
  'The three major forest biomes are coniferous forests, deciduous forests, and tropical rain forests.',
  'Their main trees are evergreen conifers which produce seeds in cones.',
  'The weather during the winter is cold, but when snow melts in the spring, some parts of the forest become swamps.',
  'There are not many different types of trees in coniferous forests because of the cold weather, and the poor soil.',
  'Fallen branches, needles, and dead animals do not decay as fast as in warmer regions.',
  'This is why the soil in coniferous forests is not very fertile.',
  'Also, only those trees that have adapted to cold weather and poor soil can survive.',
  'These trees have flexible branches that support heavy snowfalls.',
  'Summers are warm and winters are cold, but not as cold as the northern coniferous forests.',
  'In the winter, snow covers the ground and the deciduous trees and plants lose their leaves.',
  'The decaying leaves help make the soil rich in nutrients.',
  'Many insects, spiders, snails, and worms make their homes in this rich soil.',
  'Wild flowers and ferns grow almost everywhere in the spring.',
  'Many small animals hibernate or aestivate, in other words, slow down their metabolism and sleep or stay in their burrows.',
  'Some of the other animals just slow down their metabolism and eat food they stored during the summer and fall months.',
  'The trees in winter are bare, but with the coming of spring, leaves sprout, birds return, animals are born, and all the forest animals get busy with their lives.',
  'Some deciduous forests grow in tropical places that do not have a winter but do have a wet season and a dry season.',
  'Tropical rainforests are aptly named, as it rains here on about half the days.',
  'Trees are tall and thick in the rain forest and they grow so close together that they seem to form a big umbrella of greenery called a canopy.',
  'This blocks out most of the sunlight.',
  'The air is muggy as it filters through the dense canopy cover of the trees.',
  'The light that filters through this tree cover is dim and green.',
  'Only along river banks and in places that have been cleared does enough sunlight allow plants to grow on the forest ground.',
  "Millions of species of plants and animals live in the world's tropical forests.",
  'Life in the rain forest exists at different levels or layers in the trees.',
  'Animal life is found on all levels.',
]

;`
// paste this into https://simple.m.wikipedia.org/wiki/1910_Cuba_hurricane
// also see https://simple.m.wikipedia.org/wiki/Wikipedia:Very_good_articles
console.log(JSON.stringify(Array.from(document.querySelectorAll('p')).map(el => el.innerText).join(' ').split(/\.\s+/).map(s => {
s = s.trim()
s = s.replace(/\s*\[[^\]]+\]\s*/g, ' ')
s = s.replace(/\s*\([^\)]+\)\s*/g, ' ')
if (s.match(/[^A-Za-z,'\s]/)) return
if (s.length < 20) return
if (s.length > 160) return
if (s.split(/[A-Z]/).length > 3) return
s = s.trim() + '.'
return s
})
.filter(Boolean)))
`

const sentences = [...simpleSentences].sort(
  (a: string, b: string) => a.length - b.length
)

export default sentences
